apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - image:  asia.gcr.io/concise-orb-329505/myspring:v2
        name: spring-app
        envFrom:
          # Use secret in real usage
        - secretRef:  
            name: spring-secret
        - configMapRef:
            name: spring-config
        ports:
          - containerPort: 8080
          

---   
apiVersion: v1
kind: Service
metadata:
  name: spring-app-loadbalancer
spec:
  selector:
    app: spring-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080